version: "3.7"
services:
  ts-authkey-test:
    image: tailscale/tailscale:latest
    container_name: ts-authkey-test
    hostname: authkey-test
    environment:
      - TS_CLIENT_ID=${TS_CLIENT_ID} # Sử dụng biến môi trường từ GitHub Actions
      - TS_CLIENT_SECRET=${TS_CLIENT_SECRET} # Sử dụng biến môi trường từ GitHub Actions
      - TS_STATE_DIR=/var/lib/tailscale # Mặc định
      - TS_USERSPACE=false # Mặc định
    volumes:
      - ./ts-state:/var/lib/tailscale # Mặc định lưu trữ trạng thái Tailscale
    devices:
      - /dev/net/tun:/dev/net/tun # Mặc định để tạo giao diện mạng ảo
    cap_add:
      - net_admin # Mặc định để cấp quyền mạng cho container
    restart: unless-stopped # Mặc định để tự động khởi động lại nếu cần

  httpbin-test:
    image: kennethreitz/httpbin
    container_name: httpbin-test
    network_mode: service:ts-authkey-test # Chia sẻ mạng với Tailscale container
    ports:
      - "80:80" # Mở cổng 80 để truy cập httpbin
    restart: unless-stopped # Mặc định để tự động khởi động lại nếu cần
